services:
  cargo_delivery_db:
    image: postgres:18.4-bookworm
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data